apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-order
  labels:
    app: selenium-hub-order
spec:
  ports:
  - protocol: "TCP"
    port: 4444
    targetPort: 4444
    name: port0
  selector:
    app: selenium-hub-order
  type: NodePort
  # type: LoadBalancer
  # sessionAffinity: None
  # externalIPs:
  #   - 192.168.64.2