apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub-invest
  labels:
    app: selenium-hub-invest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub-invest
  template:
    metadata:
      labels:
        app: selenium-hub-invest
    spec:
      containers:
      - name: selenium-hub-invest
        image: selenium/hub:3.141
        ports:
          - containerPort: 4444
        # resources:
        #   limits:
        #     memory: "1000Mi"
        #     cpu: ".5"
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 5
          timeoutSeconds: 1
